#!/bin/bash
#PBS -l nodes=1:ppn=4,walltime=1:00:00,vmem=40gb
#PBS -N app-sift2
#PBS -V

# set -e

# run sift2
time singularity exec -e docker://brainlife/mrtrix3:3.0.3 ./run.sh

# if [ ! -f ./connectomes/density.csv ]; then
# 	echo "something failed. check derivatives"
# else
# 	echo "connectome generation completed"
# 	rm -rf *.mif *.txt
# 	mkdir -p output
# 	mv connectomes output/output/
# 	cp netneuro/surfaces/index.json ./netneuro/labels.json
# fi
